name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          # 使用 pnpm

          # 安装 pnpm
      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies using pnpm
        run: pnpm install

      - name: Build
        run: pnpm run build:github

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist-pro

